HISTFILE=~/.zsh_history
SAVEHIST=25000
HISTSIZE=25000

setopt AUTO_CONTINUE
setopt NO_AUTO_MENU
setopt NO_AUTO_REMOVE_SLASH
setopt NO_CHECK_JOBS
setopt NO_CLOBBER
setopt NO_HUP
setopt NO_SHARE_HISTORY
