HISTFILE=~/.zsh_history
SAVEHIST=100000
HISTSIZE=100000

setopt AUTO_CONTINUE
setopt NO_AUTO_MENU
setopt NO_AUTO_REMOVE_SLASH
setopt NO_CHECK_JOBS
setopt NO_CLOBBER
setopt NO_HUP
setopt NO_SHARE_HISTORY
